# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('avatar_path', models.CharField(max_length=1024)),
                ('attend_count', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('scheduled_date', models.DateTimeField(verbose_name='when the lecture happen')),
                ('teacher_name', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=100)),
                ('scan_code', models.CharField(max_length=1024)),
                ('attendees', models.ManyToManyField(to='vst.Attendee')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=1024)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='when the review is added')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='when the review is updated')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vst.Lecture')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vst.Attendee')),
            ],
        ),
    ]
