# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vst', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['scheduled_date']},
        ),
        migrations.AlterField(
            model_name='lecture',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='vst.Attendee'),
        ),
    ]
