# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vst', '0004_auto_20171005_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='when the review is added')),
            ],
        ),
    ]
